[platformio]
src_dir = Src
include_dir = Inc

[env:sstdart]
platform = ststm32
board = disco_f072rb
framework = stm32cube

build_flags =
    -DSTM32F072xB
    -DUSE_HAL_DRIVER
    -IInc
    -IDrivers/CMSIS/Include
    -IDrivers/CMSIS/Device/ST/STM32F0xx/Include
    -IDrivers/STM32F0xx_HAL_Driver/Inc
    -IDrivers/STM32F0xx_HAL_Driver/Inc/Legacy
    -IDrivers/BSP/STM32F072B-Discovery